### ISSUE TITLE
Isodyn needs to receive a maximum number of iterations as a command line argument

### ISSUE THREAD

**Issue by pcm32** [seliv55/isodyn#4]
In the current scheme, Isodyn won't stop unless that the user interrupts the process, however for workflow environment, Isodyn needs to stop on its own after  a desired number of iterations have been completed.

**Comment by seliv55** [comment]
Now Isodyn stops after saving the fixed number of files with modified parameters that is specified by the third parameter, e.g.:
isodyn.out midcorout.csv out/1 5
in this case it stops after saving 5 files during fitting

**Comment by pcm32** [comment]
For the record, this was sorted as part of this [commit](https://github.com/seliv55/isodyn/commit/1321df63c21473a21cb6089304e3251fcec90ece).

**Comment by pcm32** [comment]
@seliv55 I have tested this, but because you're exiting through an exception, it is badly handled in Kubernetes/Galaxy. The expected behaviour, when achieving a number of iterations would be a proper `exit(0)`, as the program is not exiting due to an error.

**Comment by seliv55** [comment]
OK, I will change the way of exit

**Comment by seliv55** [comment]
I changed the way of exit. Now the code stops after saving the indicated by 3-d parameter number of files by normal "return 0;" from main().
 exit(0) is not good because it does not check proper destruction of all the created objects.
